---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker
    tag: latest

inputs:
- name: project

outputs:
- name: result

run:
  path: project/ci/scripts/example2-task.sh
