resource_types:
- name: injectyy
  type: docker-image
  source:
    repository: injectyy/docker-compose
    tag: latest

resources:
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse-resdir.git
- name: injecty
  type: injectyy

jobs:
- name: example_task
  public: true
  plan:
  - get: project
  - get: injecty

  - task: example
    file: project/ci/tasks/example_task.yml
